# Generated by Django 2.1.5 on 2019-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideacreate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_word', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SecondWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_word', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_word', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
