# Generated by Django 2.1.1 on 2019-06-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanage', '0002_auto_20190602_1437'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCreate',
            new_name='Task',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
